package com.eagletelecom.app;

import android.app.*;import android.os.*;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.widget.*;import androidx.appcompat.app.AppCompatActivity;import java.util.*;

public class MainActivity extends AppCompatActivity{
 LinearLayout root,body; final int BLUE=Color.rgb(21,101,192), DARK=Color.rgb(23,32,51), MUTED=Color.rgb(102,112,133); float balance=1250; ArrayList<String> tx=new ArrayList<>();
 int d(float x){return (int)(x*getResources().getDisplayMetrics().density+.5f);} GradientDrawable bg(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(d(r));return g;}
 TextView text(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setPadding(d(14),d(9),d(14),d(9));return t;}
 Button button(String s){Button b=new Button(this);b.setText(s);b.setTextSize(15);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setBackground(bg(BLUE,18));return b;}
 EditText field(String hint){EditText e=new EditText(this);e.setHint(hint);e.setSingleLine(true);e.setTextSize(15);e.setPadding(d(15),0,d(15),0);e.setBackground(bg(Color.WHITE,16));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,d(52));p.setMargins(0,d(6),0,d(6));e.setLayoutParams(p);return e;}
 public void onCreate(Bundle b){super.onCreate(b);login();}
 void base(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(245,247,251));setContentView(root);}
 void head(String title){LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);h.setBackgroundColor(BLUE);TextView back=text("‹",34,Color.WHITE);back.setGravity(Gravity.CENTER);h.addView(back,new LinearLayout.LayoutParams(d(48),d(54)));TextView t=text(title,20,Color.WHITE);t.setTypeface(null,1);h.addView(t,new LinearLayout.LayoutParams(0,d(54),1));back.setOnClickListener(v->home());root.addView(h);}
 void login(){base();LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(d(22),d(38),d(22),d(20));root.addView(b,new LinearLayout.LayoutParams(-1,-1));TextView logo=text("🦅",52,BLUE);logo.setGravity(Gravity.CENTER);b.addView(logo,new LinearLayout.LayoutParams(-1,d(68)));TextView title=text("Eagle Telecom",28,DARK);title.setGravity(Gravity.CENTER);title.setTypeface(null,1);b.addView(title);TextView sub=text("নিরাপদ ও সহজ টেলিকম সেবা",15,MUTED);sub.setGravity(Gravity.CENTER);b.addView(sub);EditText phone=field("মোবাইল নম্বর");EditText pin=field("৬ সংখ্যার পাসওয়ার্ড / PIN");pin.setInputType(2|16);b.addView(phone);b.addView(pin);Button l=button("লগইন");b.addView(l,new LinearLayout.LayoutParams(-1,d(52)));TextView f=text("পাসওয়ার্ড ভুলে গেছেন?",14,BLUE);f.setGravity(Gravity.CENTER);b.addView(f);Button r=button("নতুন অ্যাকাউন্ট তৈরি করুন");r.setTextColor(BLUE);r.setBackground(bg(Color.WHITE,18));b.addView(r,new LinearLayout.LayoutParams(-1,d(52)));l.setOnClickListener(v->home());r.setOnClickListener(v->register());}
 void register(){base();head("রেজিস্ট্রেশন");ScrollView sv=new ScrollView(this);LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(d(20),d(15),d(20),d(25));sv.addView(b);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));TextView t=text("নতুন অ্যাকাউন্ট",24,DARK);t.setTypeface(null,1);b.addView(t);b.addView(text("বাংলাদেশ",14,MUTED));b.addView(field("Referral / Reseller Agent Code (ঐচ্ছিক)"));EditText n=field("পূর্ণ নাম");b.addView(n);EditText p=field("+880 মোবাইল নম্বর");b.addView(p);EditText a=field("৬ সংখ্যার পাসওয়ার্ড");a.setInputType(2|16);b.addView(a);EditText c=field("পাসওয়ার্ড নিশ্চিত করুন");c.setInputType(2|16);b.addView(c);Button ok=button("পরবর্তী");b.addView(ok,new LinearLayout.LayoutParams(-1,d(52)));TextView in=text("অ্যাকাউন্ট আছে? লগইন",15,BLUE);in.setGravity(Gravity.CENTER);b.addView(in);ok.setOnClickListener(v->{if(n.getText().length()<2||p.getText().length()<8||a.getText().length()!=6||!a.getText().toString().equals(c.getText().toString()))Toast.makeText(this,"তথ্যগুলো সঠিকভাবে পূরণ করুন",0).show();else{Toast.makeText(this,"রেজিস্ট্রেশন সফল (Demo)",0).show();home();}});in.setOnClickListener(v->login());}
 void home(){base();LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);h.setPadding(d(15),0,d(8),0);h.setBackgroundColor(BLUE);TextView t=text("🦅 Eagle Telecom",20,Color.WHITE);t.setTypeface(null,1);h.addView(t,new LinearLayout.LayoutParams(0,d(58),1));Button pr=button("☰");pr.setBackgroundColor(Color.TRANSPARENT);h.addView(pr,new LinearLayout.LayoutParams(d(55),d(58)));pr.setOnClickListener(v->profile());root.addView(h);ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(d(14),d(14),d(14),d(25));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(d(18),d(10),d(18),d(14));card.setBackground(bg(BLUE,22));card.addView(text("বর্তমান ব্যালেন্স",14,Color.WHITE));card.addView(text("৳ "+String.format(Locale.US,"%.2f",balance),30,Color.WHITE));body.addView(card);body.addView(text("সেবা সমূহ",20,DARK));String[][] m={{"📱","মোবাইল রিচার্জ"},{"➕","অ্যাড মানি"},{"💸","সেন্ড মানি"},{"🏦","ব্যাংক ট্রান্সফার"},{"🧾","বিল পে"},{"🎁","অফার"},{"📜","ট্রানজেকশন"},{"👤","প্রোফাইল"},{"🛟","কাস্টমার কেয়ার"},{"⚙","অ্যাডমিন প্যানেল"}};for(String[] x:m){Button q=button(x[0]+"  "+x[1]);q.setTextColor(DARK);q.setBackground(bg(Color.WHITE,16));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,d(54));lp.setMargins(0,d(5),0,d(5));body.addView(q,lp);q.setOnClickListener(v->route(x[1]));}}
 void route(String s){if(s.equals("মোবাইল রিচার্জ"))recharge();else if(s.equals("অফার"))offers();else if(s.equals("ট্রানজেকশন"))transactions();else if(s.equals("প্রোফাইল"))profile();else if(s.equals("অ্যাডমিন প্যানেল"))admin();else form(s);}
 void recharge(){form("মোবাইল রিচার্জ");}
 void form(String title){base();head(title);LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(d(20),d(20),d(20),d(20));root.addView(b);EditText one=field(title.equals("মোবাইল রিচার্জ")?"মোবাইল নম্বর":"প্রাপকের/অ্যাকাউন্ট নম্বর");EditText two=field("টাকার পরিমাণ");two.setInputType(2);b.addView(one);b.addView(two);Button ok=button("সাবমিট");b.addView(ok,new LinearLayout.LayoutParams(-1,d(52)));ok.setOnClickListener(v->{tx.add(title+" • "+one.getText()+" • ৳"+two.getText());Toast.makeText(this,"Demo request তৈরি হয়েছে",0).show();});}
 void offers(){base();head("অফার");LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(d(16),d(16),d(16),d(16));root.addView(b);b.addView(text("🔥 বিশেষ রিচার্জ অফার",20,DARK));b.addView(text("৳100+ রিচার্জে অফার প্রযোজ্য — Demo\n\n🎁 নতুন গ্রাহক বোনাস\nবাস্তব অফার backend থেকে আসবে।",16,MUTED));}
 void transactions(){base();head("ট্রানজেকশন");LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(d(16),d(16),d(16),d(16));root.addView(b);if(tx.isEmpty())b.addView(text("এখনও কোনো ট্রানজেকশন নেই।",16,MUTED));for(String s:tx)b.addView(text("• "+s,15,DARK));}
 void profile(){base();head("প্রোফাইল");LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(d(20),d(20),d(20),d(20));root.addView(b);b.addView(text("👤 Eagle Telecom User",22,DARK));b.addView(text("মোবাইল: +880XXXXXXXXXX\nReferral Code: EAGLE123",15,MUTED));Button c=button("পাসওয়ার্ড পরিবর্তন");b.addView(c,new LinearLayout.LayoutParams(-1,d(52)));Button o=button("লগআউট");b.addView(o,new LinearLayout.LayoutParams(-1,d(52)));o.setOnClickListener(v->login());}
 void admin(){base();head("Admin Panel — Demo");LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(d(16),d(16),d(16),d(16));root.addView(b);b.addView(text("Eagle Telecom Admin",24,DARK));String[] a={"👥 Users","💰 Balance Add / Deduct","📱 Recharge Requests","💳 Add Money Requests","🎁 Offers Management","🔔 Notifications","🧾 Transactions","🛟 Customer Support","⚙ Settings"};for(String s:a){Button x=button(s);x.setTextColor(DARK);x.setBackground(bg(Color.WHITE,16));b.addView(x,new LinearLayout.LayoutParams(-1,d(52)));}b.addView(text("Demo panel. Real money/recharge actions require secure backend, merchant/API credentials and authentication.",14,MUTED));}
}
